// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoCDqZ8fIUIqxYkka_VlL5AjmmLI1qP24',
    appId: '1:522253592483:web:f16b301b17aa73f04c9c16',
    messagingSenderId: '522253592483',
    projectId: 'brikolik-mvp',
    authDomain: 'brikolik-mvp.firebaseapp.com',
    storageBucket: 'brikolik-mvp.firebasestorage.app',
    measurementId: 'G-3TQNBZY80X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvu6jrEclErGtf4xwAIA4p4moDAa02OXU',
    appId: '1:522253592483:android:6e7a01843e784a944c9c16',
    messagingSenderId: '522253592483',
    projectId: 'brikolik-mvp',
    storageBucket: 'brikolik-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt5hKG4J9MsTQVjo-AeNvcv_S9v7HbUMk',
    appId: '1:522253592483:ios:d98eaa42e01ebbdc4c9c16',
    messagingSenderId: '522253592483',
    projectId: 'brikolik-mvp',
    storageBucket: 'brikolik-mvp.firebasestorage.app',
    iosBundleId: 'com.example.brikolikMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt5hKG4J9MsTQVjo-AeNvcv_S9v7HbUMk',
    appId: '1:522253592483:ios:d98eaa42e01ebbdc4c9c16',
    messagingSenderId: '522253592483',
    projectId: 'brikolik-mvp',
    storageBucket: 'brikolik-mvp.firebasestorage.app',
    iosBundleId: 'com.example.brikolikMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoCDqZ8fIUIqxYkka_VlL5AjmmLI1qP24',
    appId: '1:522253592483:web:691181ecc6e816184c9c16',
    messagingSenderId: '522253592483',
    projectId: 'brikolik-mvp',
    authDomain: 'brikolik-mvp.firebaseapp.com',
    storageBucket: 'brikolik-mvp.firebasestorage.app',
    measurementId: 'G-GWKWPTVG9F',
  );
}
